root_path: /fs-computility/llm/shared/wangyikun/dump/ad_preference_0326_segmented
internembedder_datasets:
  - name: Haijun_Preference
    data_type: s2s
    task_type: Preference
    prompts: [""]
    sampling_ratio: 1.0